### PR TITLE
Catch errors before first middleware call

### PR DESCRIPTION
**Pull request by sameoldmadness**
If exception is thrown before first middleware call, it would result in "Unhandled rejection" console message.

I assume the error could be safely ignored at this time, because it would be handled during middleware call.

### CODE REVIEW

**Comment by floatdrop** [comment]
Thanks for PR. I really don't think, that silencing exception from first run is good idea. Maybe it is better to remember last error and if there is no cached results - propagate it to response?

**Comment by sameoldmadness** [comment]
It seems to me that the code does exactly what you suggest.

Exception from the _most recent_ call is propagated to the response. No matter whether it is thrown in the initial or in subsequent calls.

**Comment by sameoldmadness** [comment]
It may be worth noting that the error is [already silenced](https://github.com/floatdrop/memorize-middleware/blob/b0e0418ad941009368ceac1e8affb6b5f362a123/index.js#L48) the same way for subsequent calls.

**Comment by sameoldmadness** [comment]
Here's another way to look at this.

```diff
- var cache = middlewarePromise();
+ var cache;

- cache.catch(nop);

function updateLoop() {
    var promise = middlewarePromise();
+   cache = cache || promise;
    promise
        .then(function () {
            cache = promise;
            setupUpdate();
        }, setupUpdate);
}

- setupUpdate();
+ updateLoop();
```

**Comment by floatdrop** [comment]
Okay, now I finally get it.

**Pull request merged**
